name: Deploy to development

on:
  push:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YAAUTH }}
          function_id: ${{ secrets.TEST_FUNCTION_ID }}
          runtime: 'python37-preview'
          memory: '128'
          environment: DEBUG=True
          entrypoint: 'dairy.main.handler'
          source: './'
          exclude: '*.jpg'
